// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFQxtRUoLdoXP_f_O5EJztbQtp5EJ5jOU',
    appId: '1:548944542997:web:f2e047c36cd082472ebd1c',
    messagingSenderId: '548944542997',
    projectId: 'smart-petition-app',
    authDomain: 'smart-petition-app.firebaseapp.com',
    storageBucket: 'smart-petition-app.firebasestorage.app',
    measurementId: 'G-VQ4Q9PK2K0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqenaNo2Vp8A6kl3YmysEPxT0BoqC-tAU',
    appId: '1:548944542997:android:bf6b61b6c3b3cae42ebd1c',
    messagingSenderId: '548944542997',
    projectId: 'smart-petition-app',
    storageBucket: 'smart-petition-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Z2jRZlqkvkoa7g_ovx65NulprAW45pU',
    appId: '1:548944542997:ios:61b40197fda7ff872ebd1c',
    messagingSenderId: '548944542997',
    projectId: 'smart-petition-app',
    storageBucket: 'smart-petition-app.firebasestorage.app',
    iosBundleId: 'com.example.smartPetitionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2Z2jRZlqkvkoa7g_ovx65NulprAW45pU',
    appId: '1:548944542997:ios:61b40197fda7ff872ebd1c',
    messagingSenderId: '548944542997',
    projectId: 'smart-petition-app',
    storageBucket: 'smart-petition-app.firebasestorage.app',
    iosBundleId: 'com.example.smartPetitionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFQxtRUoLdoXP_f_O5EJztbQtp5EJ5jOU',
    appId: '1:548944542997:web:fbfa7f69d803382e2ebd1c',
    messagingSenderId: '548944542997',
    projectId: 'smart-petition-app',
    authDomain: 'smart-petition-app.firebaseapp.com',
    storageBucket: 'smart-petition-app.firebasestorage.app',
    measurementId: 'G-5YQXV5MGKC',
  );
}
